# -*- coding: utf-8 -*-
"""FinalModel.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1V0QPV5acbdx91F-i3x-67VP4VEiFb7qF
"""

pip install streamlit lasio pandas numpy scikit-learn xgboost matplotlib

import joblib
from xgboost import XGBClassifier # or XGBRegressor, depending on your task

model = joblib.load('model.pkl')

joblib.dump(model, 'model.pkl')

